# Generated by Django 5.0.7 on 2024-07-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
